name: 更新检查器

env:
  REPO_URL: https://github.com/immortalwrt/immortalwrt
  REPO_BRANCH: master

on:
  workflow_dispatch:
  schedule:
    - cron: 0 16 * * *

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
    - name: 获取最新 Commit Hash
      id: getHash
      run: |
        git clone --depth 50 --filter=blob:none -b $REPO_BRANCH $REPO_URL repo
        cd repo
        pureHash=$(git log -1 --format="%H" -- target/linux/x86 target/linux/generic package include scripts toolchain Makefile feeds.conf.default)
        echo "commitHash=$pureHash" >> $GITHUB_OUTPUT

    - name: 对比 Commit Hash
      id: cacheHash
      uses: actions/cache@v4
      with:
        path: .commitHash
        key: X86-CORE-${{ steps.getHash.outputs.commitHash }}

    - name: 保存新 Commit Hash
      if: steps.cacheHash.outputs.cache-hit != 'true'
      run: |
        echo ${{ steps.getHash.outputs.commitHash }} > .commitHash

    - name: 触发编译工作流
      if: steps.cacheHash.outputs.cache-hit != 'true'
      uses: peter-evans/repository-dispatch@v3
      with:
        token: ${{ secrets.ACTIONS_TRIGGER_PAT }}
        event-type: Source Code Update

    - name: 清理旧的 Workflow 运行记录
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        runs=$(gh run list -w "${{ github.workflow }}" -R ${{ github.repository }} --limit 100 --json databaseId -q '.[].databaseId' | tail -n +4)
        for run in $runs; do
          if [ -n "$run" ]; then
            gh run delete "$run" -R ${{ github.repository }} || true
          fi
        done
